services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/workspace:cached
    working_dir: /workspace
    command: bash -lc "sleep infinity"
    ports:
      - "4321:4321"
    environment:
      - NODE_ENV=development
      - HOST=0.0.0.0
      - PORT=4321
